shinyUI(
    dashboardPage( 
        dashboardHeader( 
            title = "Climex"
        ),
        dashboardSidebar(
            sidebarMenu( menuItem( "General", tabName = "tabGeneral",
                                  icon = icon( "bar-chart" ) ),
                        menuItem( "Likelihood", tabName = "tabLikelihood",
                                 icon = icon( "wrench", lib = "glyphicon" ) ),
                        menuItem( "Asymptotic", tabName = "tabAsymptotic",
                                 icon = icon( "check-circle-o" ) ),
                        menuItemOutput( "menu.select.data.base" ),
                        menuItemOutput( "menu.select.data.source.1" ),
                        menuItemOutput( "menu.select.data.source.2" ),
                        menuItemOutput( "menu.select.data.source.3" ),
                        menuItemOutput( "menu.data.cleaning" ) ) ),
        dashboardBody( includeCSS( "www/climex.css" ),
                      tabItems(
                          tabItem( tabName = "tabGeneral",
                                  fluidRow(
                                      shinydashboard::box( title = h2( "GEV fit" ), status = "primary",
                                          solidheader = TRUE,
                                          width = 8,
                                          column( 9, plotOutput( "plot.fit.gev" ) ),
                                          column( 3, plotOutput( "plot.fit.qq", height = 140 ),
                                                 plotOutput( "plot.fit.qq2", height = 140 ),
                                                 plotOutput( "plot.fit.return.level",
                                                            height = 140 ) ) ),
                                      shinydashboard::box( title = h2( "Options" ), collapsible = TRUE,
                                          width = 4, height = 550, background = "orange",
                                          radioButtons( "radio.gev.statistics", label = NULL,
                                                       inline = TRUE,
                                                       choices = c( "blocks", "threshold" ),
                                                       selected = "blocks" ),
                                          menuItemOutput( "slider.gev.statistics" ),
                                          radioButtons( "button.min.max", "Type of extreme",
                                                       inline = TRUE,
                                                       choices = c( "max", "min" ),
                                                       selected = "max" ),
                                          selectInput( "select.deseasonalize",
                                                      "Deseasonalization method",
                                                      choices = c( "Anomalies", "stl", "decompose",
                                                                  "X-13ARIMA", "deseasonalize::ds",
                                                                  "descomponer", "none" ),
                                                      selected = "Anomalies" ),
                                          selectInput( "select.optimization",
                                                      "Optimization/Fitting rountine",
                                                      choices = c( "Nelder-Mead", "CG",
                                                                  "BFGS", "SANN", "ismev::gev.fit",
                                                                  "extRemes::fevd" ),
                                                      selected = c( "Nelder-Mead" ) ) ) ),
                                  fluidRow(
                                      shinydashboard::box( title = h2( "Results" ), width = 3,
                                          background = "orange",
                                          uiOutput( "table.statistics",
                                                   colHeaders = "provided" ) ),
                                      tabBox( title = h2( "Time series" ), selected = "Blocked ts",
                                             width = 9,
                                             tabPanel( "Pure ts",
                                                      dygraphOutput( "plot.time.series",
                                                                    height = 250 ) ),
                                             tabPanel( "Deseasonalized ts",
                                                      dygraphOutput( "plot.deseasonalized",
                                                                    height = 250 ) ),
                                             tabPanel( "Blocked ts",
                                                      plotOutput( "plot.blocked", height = 250,
                                                                 click = "plot.blocked.click",
                                                                 brush = brushOpts(
                                                                     id = "plot.blocked.brush" ) ),
                                                      actionButton( "exclude.blocked.reset",
                                                                   "Reset" ),
                                                      actionButton( "exclude.blocked.toggle",
                                                                   "Brush" ) ) ) ) ),
                          tabItem( tabName = "tabLikelihood",                                  
                                  shinydashboard::box( title = h2( "Likelihood of the time series and optimization routes of different initial conditions" ),
                                      width = 7, status = "primary",
                                      dataTableOutput( "table.initial.points" ),
                                      actionButton( "table.draw.points", "Reset" ),
                                      uiOutput( "draw.likelihood.animation" ) ),
                                  shinydashboard::box( width = 5, background = "orange",
                                      dataTableOutput( "table.heuristic.estimates" ),
                                      sliderInput( "slider.number.initial.points",
                                                  "Number of initial points", 1, 20, 5 ),
                                      uiOutput( "menu.slider.location.lim" ),
                                      uiOutput( "menu.slider.scale.lim" ),
                                      uiOutput( "menu.slider.shape.lim" ),
                                      selectInput( "select.optimization.procedure.likelihood",
                                                  "Optimization procedure",
                                                  choices = c( "dfoptim::nmk",
                                                              "dfoptim::nmk.modified" ),
                                                  selected = "dfoptim::nmk" ),
                                      sliderInput( "slider.optimization.steps",
                                                  "Which optimization steps", 0, 1,
                                                  c( .1, .5 ) ),
                                      actionButton( "button.draw.animation",
                                                   "Start animation" )) ),
                          tabItem( tabName = "tabAsymptotic",
                                  h2( "Different plots for checking the fulfillment of the asymptotic" ) ) ) ) ) )
